print ("My name is Natalie")
print ("My birthday is in September!")
print ("My name is Kevin")
print ("May 11")
print ("My favorite food is pizza with pineapple")
print ("apples")
print ("oranges")
print ("I have a twin. His name is Brett. He goes to the University of Georgia")
print ("We are close. But like, we don't need each other to survive")
print ("He is coming for St.Paddys, which is March 17th btw")
